### ISSUE TITLE
compose.yaml

### ISSUE THREAD

**Issue by evabronskayaa** [FazylovV/videohosting_dwh#1]
Все-таки такой файл принято назвать docker-compose.yaml

**Comment by evabronskayaa** [comment]
Креды стоит вынести в .env

```yaml
    environment:
      MINIO_ACCESS_KEY: minio
      MINIO_SECRET_KEY: minio123
    ports:
      - 9000:9000
      - 9001:9001

    environment:
      POSTGRES_DB: dwh
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 5432
    ports:
      - 5432:5432
```

**Comment by evabronskayaa** [comment]
Для мониторирования вольюмов обычно достаточно проектных путей

```yaml
    volumes:
      - C:\Users\vladi\Documents\Docker\dwh\data:/data

    volumes:
      - C:\Users\vladi\Documents\Docker\dwh\postgres_data:/var/lib/postgresql/data
```
